# Generated by Django 5.1.1 on 2024-09-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_title_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='posters/default_poster.png', upload_to='posters/'),
        ),
    ]
